BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[account] ALTER COLUMN [accessToken] NVARCHAR(max) NULL;
ALTER TABLE [dbo].[account] ALTER COLUMN [refreshToken] NVARCHAR(max) NULL;
ALTER TABLE [dbo].[account] ALTER COLUMN [idToken] NVARCHAR(max) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
